/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sheiladwi;

import javax.swing.*;

/**
 *
 * @author sheil
 */
public class formMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form formMenuUtama
     */
    public formMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mbData = new javax.swing.JMenu();
        mdData = new javax.swing.JMenuItem();
        mbTransaksi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mbData.setText("Menu Utama");
        mbData.setFont(new java.awt.Font("MS Gothic", 0, 24)); // NOI18N

        mdData.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        mdData.setText("Data pembeli");
        mdData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdDataActionPerformed(evt);
            }
        });
        mbData.add(mdData);

        mbTransaksi.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        mbTransaksi.setText("Transaksi");
        mbTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbTransaksiActionPerformed(evt);
            }
        });
        mbData.add(mbTransaksi);

        jMenuBar1.add(mbData);

        jMenu2.setText("Kembali");
        jMenu2.setFont(new java.awt.Font("MS Gothic", 0, 24)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbTransaksiActionPerformed
        formTransaksi form2 = new formTransaksi();
        form2.setExtendedState(JFrame.MAXIMIZED_BOTH);
        form2.setVisible(true);
    }//GEN-LAST:event_mbTransaksiActionPerformed

    private void mdDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdDataActionPerformed
        formData form1 = new formData();
        form1.setExtendedState(JFrame.MAXIMIZED_BOTH);
        form1.setVisible(true);
    }//GEN-LAST:event_mdDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbData;
    private javax.swing.JMenuItem mbTransaksi;
    private javax.swing.JMenuItem mdData;
    // End of variables declaration//GEN-END:variables
}
